Two theorems implying CWN
pi-base/data pull request #1007
Opened 2024-12-04 07:05 UTC by prabau

work in progress.

2024-12-04 20:56 UTC, prabau commented
@StevenClontz The build for this branch `cwn2` succeeds, but for some reason I am unable to preview it on the web site.
For some reason, the initial updating of the traits gets stuck.  Any idea?

If nothing else works, I'll try to redo it in another branch.

2024-12-04 22:10 UTC, StevenClontz commented
possibly related: https://github.com/pi-base/web/issues/200 (in that case, I know I introduced an error for the Empty space, but it wasn't caught at compilation)

2024-12-04 23:21 UTC, prabau commented
Interesting.  For me, when going to the Advanced tab and trying to preview the new branch, the initial updating of all the traits (as indicated by the progress of the green bar) gets stuck half way through and it never finishes.  Was that the same symptom you were having?

2024-12-04 23:39 UTC, GeoffreySangston commented
I've had a similar issue. On chrome you can clear the cache for a single website: chrome://settings/content/all?searchSubpage=pi-base, and this may fix the issue.

2024-12-04 23:57 UTC, prabau commented
Thanks for the tip.  In this case it did not help.  I'll try something else.

2024-12-05 04:33 UTC, yhx-12243 requested changes
Maybe it is caused by the contradiction due to your typo (... + ~Normal ⇒ CWN) and (... + $T_4$ ⇒ CWN).

However, as pi-base/web#200 said, it wasn't caught on build (yes I cloned a local copy of compiler and it wasn't report neither), nowadays we should fix the typo and resume, leave pi-base/web#200 continue.

2024-12-05 04:33 UTC, yhx-12243 commented on theorems/T000657.md
> +  - P000013: false
```suggestion
  - P000013: true
```

2024-12-05 04:33 UTC, yhx-12243 commented on theorems/T000658.md
> +  - P000007: false
```suggestion
  - P000007: true
```

2024-12-05 04:59 UTC, prabau commented
@yhx-12243 Very good eyes! That must be it.

2024-12-05 05:04 UTC, StevenClontz commented
Nicely spotted @yhx-12243!

I'm not sure what's happened that has caused the compiler to not catch these contradictions. 😢 But we'll need to be vigilant to ensure that things are building in the viewer until pi-base/web#200 can be addressed.

2024-12-05 06:08 UTC, prabau commented
Note: It does not seem possible to generalize T662 to [countable extent + normal => collectionwise normal].

For example, take a space $Y$ that is $T_4$ but not collectionwise normal.  For example S136 (Bing's Example G).
Let $X=Y\times B$, where $B$ is a two-point set with the indiscrete topology.
Then $X$ is weakly countably compact (= limit point compact) because every nonempty set has a limit point.
And it is normal, but not collectionwise normal (by looking at the Kolmogorov quotient, which is homeomorphic to $Y$.

2024-12-06 07:05 UTC, yhx-12243 approved these changes

2024-12-06 09:07 UTC, merged