Fix S72 tuple notation
pi-base/data pull request #1092
Opened 2024-12-15 23:59 UTC by StevenClontz

Closes #1089

2024-12-16 00:44 UTC, GeoffreySangston commented on spaces/S000072/README.md
> +This space is $X$ where $S$ has its subspace topology from {S176}, and
```suggestion
This space is $X$, where $S$ has its subspace topology from {S176}, and
```

2024-12-16 01:07 UTC, prabau commented
I am comparing what we have in pi-base and what S&S have for the "Arens square", and there is a major discrepancy between the two descriptions.

S&S take $S$ to be the set of **rational** lattice points in the interior of the unit square except those whose $x$-coordinate is $1/2$.  The description in pi-base needs to be fixed.
(Compare with [S80 ](https://topology.pi-base.org/spaces/S000080) (B. Scott's modified Arens square), which is carefully worded.)

2024-12-16 01:45 UTC, StevenClontz commented
Thanks @prabau I'll address that feedback and mark as ready when it's done.

2024-12-17 04:22 UTC, prabau commented
Hmm, sorry but this is not correct.  This does not match the description in Steen & Seebach.

2024-12-17 04:24 UTC, prabau requested changes
Need to match the description in S&S.

2024-12-17 04:41 UTC, StevenClontz commented
Er, sure. I could have easily made a mistake, but it would be more helpful if you pointed out where you think that mistake is.

2024-12-17 05:38 UTC, prabau commented
Need to exclude from $S$ the points with $x$-coordinate equal to 1/2.

The notation with subscript $\mathbb Q$ is ok, but not really needed I think.

If it's ok with you, I could give a try to "fix" the remaining problems. It's possible to express all this in a not too difficult way.

2024-12-17 18:35 UTC, prabau commented
Please accept my apology for this uncooperative comment.  I was getting tired last night, but it's no excuse.

2024-12-18 22:54 UTC, StevenClontz commented
I appreciate the apology.

Note that I was using the first edition when I made this PR:

![image](https://github.com/user-attachments/assets/c2b5a514-14e0-4d06-a2e1-19f8efb49703)

But I see (now that I'm in my office) a later edition corrects $S$ to not include the x-coordinate $\frac{1}[2}$. I'd have had a lot of trouble finding this discrepancy without you adding the detail on the error you found. Marking as draft and will address (and point out discrepancy) when I can.

2024-12-18 22:57 UTC, StevenClontz commented
![PXL_20241218_225544002](https://github.com/user-attachments/assets/d74c3469-f4b1-4bb0-88b6-33a2b93d7c73)

For comparison.

2024-12-31 19:05 UTC, prabau commented
It seems to me that the previous way of describing thing without using interval notation was maybe clearer.  For example, for $U_n(0,0)$ we could have used something like:
$U_n(0,0) = \\{\langle 0,0\rangle\\} \cup \\{\langle x,y\rangle\in X: 0<x<\frac{1}{4}, 0<y<\frac{1}{n}\\}$.

But the current description is correct at least.  So approving.

2024-12-31 19:06 UTC, prabau approved these changes

2025-01-10 04:02 UTC, merged