add another example of a finite disconnected space
pi-base/data pull request #473
Opened 2023-11-22 19:05 UTC by StevenClontz

2023-11-22 23:50 UTC, prabau requested changes

2023-11-22 23:50 UTC, prabau commented on spaces/S000184/README.md
> +$X=X_0\cup X_1$ with each $X_i$ open and a copy of {S4}.
use sqcup instead of cup to indicate the two subsets are disjoint

2023-11-22 23:50 UTC, prabau commented on spaces/S000184/properties/P000036.md
> +By construction as the union of two proper nonempty open sets.
Need "disjoint union" instead of just "union".  Given "nonempty", can drop "proper" if we use "disjoint union".

2023-11-26 18:05 UTC, StevenClontz commented on spaces/S000184/properties/P000125.md
> +property: P000125
Should be upgraded to P176 after #471 is merged.

2023-11-26 20:18 UTC, prabau approved these changes

2023-11-26 20:19 UTC, merged